import React from 'react'
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-3xl uppercase text-center">contact</p>
    </div>
  );
}

export default Contact