import React from 'react'
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-3xl uppercase text-center">about</p>
      <div className='w-[50%] mx-auto mt-5 text-center'>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Incidunt quibusdam magnam fugit natus accusantium deleniti sint fuga expedita nisi nemo soluta mollitia laboriosam ad, quae repudiandae eos quam. Amet, possimus.</p>
      </div>
    </div>
  );
}

export default About