export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-3xl uppercase text-center">home</p>
    </div>
  );
}
