import React from 'react'
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-3xl uppercase text-center">login</p>
    </div>
  );
}

export default Login