import React from 'react'
export const metadata = {
  title: "Sign up",
  description: "Generated by create next app",
};

const Signup = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-3xl uppercase text-center">sign up</p>
    </div>
  );
}

export default Signup